/* SECUENCIA (SEQUENCE): ES UN BLOQUE PL/SQL QUE GENERA NUMEROS SECUENCIALES EN
AUTOMATICO.

GENERALMENTE SE USA PARA GENERAR LLAVES PRIMARIAS ASEGURANDO QUE LOS VALORES 
SERAN UNICOS.*/

CREATE SEQUENCE ID_BIT_CEL_SEQ --NOMBRE DE LA SECUENCIA
START WITH 1
MINVALUE 1
MAXVALUE 99
NOCYCLE; --una vez que llegue a su valor maximo, no se podra utilizar.

SELECT ID_BIT_CEL_SEQ.NEXTVAL FROM DUAL;
