/* TRIGGERS (DISPARADORES): Es un bloque de codigo que se ejecuta 
 automaticamente en respuesta a ciertos eventos en una tabla o vista.
 Se disparan cuando ocurren estas instrucciones DML en una tabla:
    INSERT
    UPDATE
    DELETE
    
  Los TRIGGERS se ocupan porque sirven para 
    - registrar auditorias(bitacoras de cambio)
    - validar reglas de negocio complejas
    - mantener integridad de los datos
    - generar valores automaticos (TIMESTAMP o el usuario que modifico USER)
  
  TIPOS DE TRIGGER
    BEFORE -> Se ejecuta antes de que ocurra la operacion
    AFTER -> Se ejecuta despues de que ocurra la operacion
    INSTEAD OF -> se usa en vistas, reemplaza la operacion DML
    
  NIVEL DEL TRIGGER
    ROW (POR FILA) -> Se activa por cada fila afectada
    STATEMENT(SENTENCIA) -> Se activa una sola vez por instruccion SQL sin 
        importar las filas que afecte
        
  VARIABLES ESPECIALES EN TRIGGER POR FILA (FOR EACH ROW) 
    :OLD -> REPRESENTA LOS VALORES ANTERIORES (ANTES DE MODIFICAR)
    :NEW -> REPRESENTA LOS VALORES NUEVOS (DESPUES DE INSERTAR O MODIFICAR)
        SOO FUNCIONA PARA TRIGER FOR EACH ROW

    ANTES DE OCUPAR UN TRIGGER QUE AFECTE COLUMNAS O SENTENCIAS QUE OTROS 
    TRIGGER PUEDAN AFECTAR, SE DEBEN DE DESACTIVAR.         
        */
        
--TRIGER SIMPLE
CREATE TABLE CELULAR(
    ID_CELULAR NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT CELU_PK PRIMARY KEY(ID_CELULAR)
);

--CREAR UNA ENTIDAD BITACORA CELULAR QUE REGISTRARA CADA EVENTO EN LA TABLA 
-- CELULAR
CREATE TABLE CELULAR_BIT(
    ID_BIT NUMBER, --CLAVE PRIMARIA DE LA BITACORA
    
    --VALORES NUUEVOS :NEW
    ID_CELULAR NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NVARCHAR2(100),
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    
    --VALORES VIEJOS :OLD
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    RAM_OLD NVARCHAR2(100),
    PROCESADOR_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BIT_PK PRIMARY KEY (ID_BIT)
);

--TRIGER SIMPLE A NIVEL SENTENCIA. ACTUARA DESPUES DE QUE OCURRA UNA OPERACION
--DE TIPO INSERT EN MI TABLA CELULAR
-- TR_I_CEL (TRIGGER INSERT CELULAR)
CREATE OR REPLACE TRIGGER TR_I_CEL
AFTER INSERT ON CELULAR -- ACTUARA DESPUES DE UNA SENTENCIA INSERT
FOR EACH ROW -- EL TRIGGER ACTUARA POR CADA FILA AFECTADA DE MI TABLA CELULAR
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL; --RECUPERACION DE USUARIO DL SISTEMA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL; --RECUPERACION DE LA FECHA DEL SISTEMA
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT; --CREA AUTOINCREMENTAL DE ID_BIT
    
    INSERT INTO CELULAR_BIT(ID_BIT, ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, 
        PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, 
        USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, 
        :NEW.PROCESADOR, :NEW.PRECIO, NULL, NULL, NULL, NULL, 0, LV_USUARIO, 
        LV_FECHA, 'INSERT');
END TR_I_CEL;


-- REALIZAR UN TRIGGER PARA LA OPERACION DE DELETE Y UN TRIGGER PARA LA OPERACION DE UPDATE

--DELETE
CREATE OR REPLACE TRIGGER TR_D_CEL
AFTER DELETE ON CELULAR -- ACTUARA DESPUES DE UNA SENTENCIA DELETE
FOR EACH ROW -- EL TRIGGER ACTUARA POR CADA FILA AFECTADA DE MI TABLA CELULAR
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL; --RECUPERACION DE USUARIO DL SISTEMA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL; --RECUPERACION DE LA FECHA DEL SISTEMA
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT; --AUTOINCREMENTO
    
    INSERT INTO CELULAR_BIT(ID_BIT, ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, 
        PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, 
        USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :OLD.ID_CELULAR, NULL, NULL, NULL, NULL, 0, :OLD.MARCA, 
        :OLD.MODELO, :OLD.RAM, :OLD.PROCESADOR,:OLD.PRECIO, LV_USUARIO, 
        LV_FECHA, 'DELETE');
END TR_D_CEL;

--UPDATE
CREATE OR REPLACE TRIGGER TR_U_CEL
AFTER UPDATE ON CELULAR -- ACTUARA DESPUES DE UNA SENTENCIA UPDATE
FOR EACH ROW -- EL TRIGGER ACTUARA POR CADA FILA AFECTADA DE MI TABLA CELULAR
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT USER INTO LV_USUARIO FROM DUAL; --RECUPERACION DE USUARIO DL SISTEMA
    SELECT SYSDATE INTO LV_FECHA FROM DUAL; --RECUPERACION DE LA FECHA DEL SISTEMA
    SELECT NVL(MAX(ID_BIT), 0) + 1 INTO LV_ID_BIT FROM CELULAR_BIT; --AUTOINCREMENTO
    
    INSERT INTO CELULAR_BIT(ID_BIT, ID_CELULAR, MARCA, MODELO, RAM, PROCESADOR, 
        PRECIO, MARCA_OLD, MODELO_OLD, RAM_OLD, PROCESADOR_OLD, PRECIO_OLD, 
        USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES (LV_ID_BIT, :NEW.ID_CELULAR, :NEW.MARCA, :NEW.MODELO, :NEW.RAM, 
        :NEW.PROCESADOR, :NEW.PRECIO, :OLD.MARCA, :OLD.MODELO, :OLD.RAM, 
        :OLD.PROCESADOR, :OLD.PRECIO, LV_USUARIO, LV_FECHA, 'UPDATE');
END TR_U_CEL;