-- VISTAS COMPLEJAS: ALMACEN DE CONSULTAS CON CLAUSULAS JOIN

CREATE TABLE VENTA(
    ID_VENTA NUMBER,
    CELULAR_ID NUMBER,
    CANTIDAD NUMBER,
    FECHA DATE,
    CONSTRAINT VENTA_PK PRIMARY KEY (ID_VENTA),
    CONSTRAINT CEL_FK FOREIGN KEY (CELULAR_ID) REFERENCES CELULAR (ID_CELULAR)
);

INSERT INTO VENTA VALUES(101, 1, 1, SYSDATE);
INSERT INTO VENTA VALUES(102, 4, 2, SYSDATE);
INSERT INTO VENTA VALUES(103, 5, 1, SYSDATE);
INSERT INTO VENTA VALUES(104, 2, 3, SYSDATE);

-- DETALLE DE LA VENTA
CREATE OR REPLACE VIEW V_VENTA_CEL AS
SELECT V.ID_VENTA, C.MARCA, C.MODELO, V.CANTIDAD, V.FECHA
FROM VENTA V
INNER JOIN CELULAR C ON V. CELULAR_ID = C.ID_CELULAR;

SELECT * FROM V_VENTA_CEL;

-- VISTA VER EL TOTAL VENDIDO POR MODELO
CREATE OR REPLACE VIEW V_TOTAL_VENTAS_MODELO AS
SELECT C.MARCA, C.MODELO, SUM(V.CANTIDAD) AS TOTAL_VENDIDO FROM CELULAR C
RIGHT JOIN VENTA V ON C.ID_CELULAR = V.CELULAR_ID
GROUP BY C.MARCA, C.MODELO;

SELECT * FROM V_TOTAL_VENTAS_MODELO; 