-- CREAR UNA ENTIDAD

--DDL (LENGUAJE DE DEFINICION DE DATOS)
CREATE TABLE EMPLEADO(
	ID_EMPLEADO NUMBER,
	NOMBRE NVARCHAR2(10),
	APATERNO NVARCHAR2(100),
	EDAD NUMBER,
	PUESTO NVARCHAR2(100),
	DEPARTAMENTO NVARCHAR2(100)
);

--DML (LENGUAJE DE MANIPULACION DE DATOS)
INSERT INTO EMPLEADO VALUES(1, 'MARTIN', 'LOPEZ', 35, 'PROGRAMADOR JAVA', 'DESARROLLO');
COMMIT; -- UNA VEZ QUE SE EJECUTA UNA SENTENCIA DML, DEBEMOS CONFIRMAR LOS CAMBIOS PARA TERMINAR CON LA TRANSACCION
ROLLBACK; -- EN LUGAR DE CONFIRMAR LOS CAMBIOS, LOS REVIERTE

SELECT * FROM EMPLEADO;

-- EJECUTAR DML PARA ELIMINAR 
DELETE FROM EMPLEADO; -- ELIMINA LOS REGISTROS DE MI TABLA
--EJECUTAR UN DDL PARA ELIMINAR
DROP TABLE EMPLEADO; -- ELIMINA TODA LA TABLA PDE LA BD

--uso de constraint
--CREAR UNA ENTIDAD CON PRIMARY KEY --> PRIMERA MANERA
CREATE TABLE EMPLEADO(
	ID_EMPLEADO NUMBER PRIMARY KEY,
	NOMBRE NVARCHAR2(100),
	EDAD NUMBER,
	PUESTO NVARCHAR2(100),
	DEPARTAMENTO NVARCHAR2(100)
);

--SEGUNDA MANERA
CREATE TABLE EMPLEADO(
	ID_EMPLEADO NUMBER;
	NOMBRE NVARCHAR2(100),
	EDAD NUMBER,
	PUESTO NVARCHAR2(100),
	DEPARTAMENTO NVARCHAR2(100),
	PRIMARY KEY(ID_EMPLEADO)
);

--TERCERA MANERA
CREATE TABLE EMPLEADO(
	ID_EMPLEADO NUMBER,
	NOMBRE NVARCHAR2(100),
    APATERNO NVARCHAR2(100),
	EDAD NUMBER,
	PUESTO NVARCHAR2(100),
	DEPARTAMENTO NVARCHAR2(100),
	CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO) --NOS ASEGURAMOS QUE NO EXISTA LA MISMA LLAVE EN OTRA TABLA, EL CAMPO SI, PERO EL CAMPO COMO LLAVE NO
);
