SELECT * FROM EMPLEADO;

INSERT INTO EMPLEADO VALUES (1, 'MARTIN', 'LOPEZ', 32, 'DESARROLLADOR JAVA', 'DESARROLLO');
INSERT INTO EMPLEADO VALUES(2, 'MELANY', 'SANCHEZ', 26, 'SECRETARIA', 'DEP. RH');
INSERT INTO EMPLEADO VALUES(3, 'ALFREDO', 'GODOFREDO', 32, 'MANAGER', 'DEP. IT');
INSERT INTO EMPLEADO VALUES(4, 'BEATRIZ', 'MARTINEZ', 29, 'ANALISTA', 'DEP. VENTAS');
INSERT INTO EMPLEADO VALUES(5, 'MAURICIO', 'RAMIREZ', 28, 'PROGRAMADOR Jr', 'DEP. IT');
INSERT INTO EMPLEADO VALUES (6, 'SUSANA', 'ORIA', 23, 'DESARROLLADOR BOOTSTRAP', 'FRONT');
INSERT INTO EMPLEADO VALUES (7, 'ALINE', 'MORALES', 25, 'DESARROLLADOR JAVA', 'DESARROLLO');
COMMIT;

--MODIFICAR O CAMBIAR EL NOMBRE DE UNA COLUMNA
ALTER TABLE EMPLEADO RENAME COLUMN APATERNO TO APELLIDO;

--ACTUALIZAR UN REGISTRO
UPDATE EMPLEADO SET NOMBRE 'MARTINA' WHERE ID_EMPLEADO = 7;

-- ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC;
SELECT * FROM EMPLEADO ORDER BY NOMBRE DESC;

--BUSQUEDA DE INFORMACION CON CARACTERES EN ESPECIFICO
--BUSCAR EMPLEADOS CUYO NOMBRE EMPIEZA CON LA LETRA A
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'A%';
--BUSCAR EMPLEADOS CUYO NOMBRE EMPIEZA CON LA LETRA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'I%';
--BUSCAR EMPLEADOS CUYO NOMBRE EMPIEZA CON LA LETRA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'O%';

--USO DE LA TABLA DUAL: ES UNA TABLA DE ORACLE A LA QUE PODEMOS ACCEDER CUANDO
-- NO SE NECESITA ACCEDER A UNA TABLA REAL.
SELECT 5+4 AS SUMA FROM DUAL
--USO DE LA FUNCION LENGTH
SELECT LENGTH('ESTE ES UN EJEMPLO DE LA FUNCION LENGTH') AS TAMANIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADO QUE TENGAN 32
SELECT * FROM EMPLEADO WHERE EDAD = 32;
-- MAYORES DE 30
SELECT * FROM EMPLEADO WHERE EDAD > 30;
-- MENORES DE 29
SELECT * FROM EMPLEADO WHERE EDAD < 29;

--EMPLEADOS MAYORES DE 25 PERO MENORES DE 27
SELECT * FROM EMPLEADO WHERE EDAD > 25 AND EDAD < 28;
--RANGO BETWEEN
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 25 AND 28;

--BUSCAR SOLO EMPLEADOS CON ID 1, 5 Y 7
SELECT * FROM EMPLEADOS WHERE ID_EMPLEADO 
--FUNCION
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1, 5, 7);

--AGRUPAR LOS EMPLEADOS POR DEPARTAMENTO (GROUP BY, COUNT)
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO GROUP BY DEPARTAMENTO;

--CONTAR CUANTOS EMPLEADOS SON MAYORES DE 25
SELECT COUN(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO GROUP BY DEPARTAMENTO;

--FUNCION SUM
SELECT SUM(EDAD) AS SUMA_EDAD FROM EMPLEADO;
SELECT SUM(EDAD) AS SUMA_EDAD FROM EMPLEADO WHERE NOMBRE LIKE '%I%';

--CUAL ES EL VALOR MAYOR
SELECT MAX (EDAD) FROM EMPLEADO

--CUAL ES EL VALOR MENOR
SELECT MIN (EDAD) FROM EDAD MINIMA;

--CUAL ES EL PROMEDIO DE LA EDAD(AVG)
SELECT AVG(EDAD) AS PROMEDIO_EDAD FROM EMPLEADO;
--PODEMOS REDONDEAR EL PROMEDIO DE LA EDAD(ROUND)
SELECT ROUND(AVG(EDAD),2) AS PROMEDIO_EDAD FROM EMPLEADO;

--DAR UN FORMATO DIFERENTE 
--USAR PIPE O BARRA LATERAL  --> ||
SELECT 'EL EMPLEADO: '||NOMBRE||' '||APELLIDO||' DE EDAD '||EDAD||' TRABAJA COMO: '||PUESTO||
	' EN EL DEPARATMENTO: '||DEPARTAMENTO AS DETALLE FROM EMPLEADO;

--SUBCONSULTA
SELECT * FROM EMPLEADO WHERE 
EDAD =(
    SELECT MIN(EDAD)
    FROM EMPLEADO WHERE DEPARTAMENTO =('DEP. IT')
    );