/* 
FUNCIONES (FUNCTION): UNA FUNCION ES UN BLOQUE QUE RECIBE PARAMETROS DE 
ENTRADA(OPCIONALES) Y EJECUTA UNA SERIE DE INSTRUCCIONES, DEVUELVE EL VALOR CON 
LA CLAUSULA RETURN

SE USA MUCHO CUANDO QUIERES REUTILIZAR CODIGO QUE SIEMPRE RETORNA UN RESULTADO
(A DIFERENCIA DEL PROCEDIMIENTO ALMACENADO QUE NO SIEMPRE RETORNA UN RESULTADO)

PUNTOS IMPORTANTES -> RETURN tipo_dato: DEFINE QUE TIPO DE VALOR REGRESARA
(NUMBER, NVARHAR2, DATE) SIEMPRE DEBE HABER AL MENOS UN RETURN EN EL BLOQUE 
BEGIN...END
    */
    
--REALIZAR UNA FUNCION QUE RECIBA 2 PARAMETROS Y REALICE UNA SUMA
CREATE OR REPLACE FUNCTION SUMA(a NUMBER, b NUMBER)
RETURN NUMBER
IS
    RESULTADO NUMBER;
BEGIN
    RESULTADO := a+b;
    RETURN RESULTADO;
END;
/

--IMPRIMIR EL RESULTADO EN DUAL
SELECT SUMA(10, 15) FROM DUAL;

--INVOCAR DESDE UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL RESULTADO DE LA SUMA ES: '|| SUMA(1,2));
END;

CREATE OR REPLACE FUNCTION AREA_CIRCULO(RADIO NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN 3.1416 * (RADIO * RADIO);
END;
/

--MEDIENTE UN CONSULTA
SELECT AREA_CIRCULO(5) FROM DUAL;
--MEDIANTE UN BLOQUE ANONIMO
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL AREA DEL CIRCULO ES: ' || AREA_CIRCULO(6));
END;
    