/*VISTAS(VIEW) ES UNA CONSULTA ALAMCENADA QUE SE GUARDA EN LA BASE DE DATOS COMO SI FUERA UNA
TABLA VIRTUAL.
NO ALMACENA DATOS FISICAMENTE SINO QUE TOMA LOS DATOS DE UNA O VARIAS TABLAS

VENTAJAS
    SIMPLIFICAN CONSULTAS: PUEDES ENCAPSULAR UNA CONSUMLTA COMPLICADA Y LUEGO CONSULTARLA COMO
    SI FUERA UN TABLA
    SEGURIDAD:SE PUEDEN DAR PERMSIOS DE ACCESO A SOLO VISTAS, OCULTANDO COLUMNAS SENSIBLES DE LA
    TABLA REAL.
    REAUTILIZACION: UNA VEZ CREADA, LA VISTA SE PUEDE USAR EN MUCHAS CONUSLTAS
    MENTENIMIENTO: SI CMABIAS LA CONUSLTA EN LA VISTA NO TIENES QUE CMABIAR TODAS LAS CONSULTAS QUE
    USANBAN ESA VISTA.
    
TIPOS DE VISTAS 
    VISTAS SIMPLES: CREADAS SOBRE UNA SOLA TABLA
    VISTAS COMPLEJAS: CREADAS A PARTIR DE VARIAS TABLAS CON JOIN, AGREGACION ETC.
    VISTAS CON OOPCION DE ACTULIZACION> EN ALGUNOS CASO(SI CUMPLE LA CONIDCION) SE PUEDEN USARA PARA
    INSERTAR O ELIMINAR REGISTROS.
    VISTAS MATERALIZADAS:ALMACCENAS RESULTADOS FISICAMENTE.
*/

SELECT * FROM CELULAR;

UPDATE CELULAR SET MARCA = 'SAMSUNG' WHERE ID_CELULAR = 11;

INSERT INTO CELULAR VALUES(11, 'SAMSUG', 'Z-FLIP', '4GB', 'OCTACORE', 10029);
INSERT INTO CELULAR VALUES(12, 'IPHONE17', 'PROMAX', '4GB', 'HEXA-CORE', 16790);

--VISTA PARA SABER CUALES SON LOS CELULARES MAS CAROS 
CREATE OR REPLACE VIEW V_CEL_CAROS AS
SELECT ID_CELULAR, MARCA, MODELO, PRECIO FROM CELULAR
WHERE PRECIO >10000;
--NO ES NECESARIO CERRARLAS

--CONSULTAR VISTA 
SELECT * FROM V_CEL_CAROS;

-- VISTA QUE ME DE LOS MODELOS POR MARCA
CREATE OR REPLACE VIEW V_MODELOS_CEL AS
SELECT MARCA, MODELO
FROM CELULAR;

SELECT * FROM V_MODELOS_CEL WHERE MARCA = 'SAMSUNG';

-- VISTA COMO CLASIFICACION
CREATE OR REPLACE VIEW V_CEL_CATEGORIA AS
SELECT MARCA, MODELO, PROCESADOR,
    CASE
        WHEN PRECIO < 6000 THEN 'ECONOMICO'
        WHEN PRECIO BETWEEN 6000 AND 11000 THEN 'GAMA MEDIA'
        ELSE 'GAMA ALTA'
    END AS CATEGORIA
FROM CELULAR;

SELECT * FROM V_CEL_CATEGORIA;