--DDL: Lenguaje de definicion de datos --> CREATE, UPDATE ALTER Y DROP
--DML: Lenguaje de manipulacion de datos --> SELECT, INSERT, UPDATE Y DELETE
--DCL: Lenguaje de control de datos --> GRANT Y REVOKE


---MODIFICAR LA SESION ACTUAL PARA LA EJECUCION DE SCRIPTS, NOS PERMITE CREAR USUARIOS
ALTER  SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREACION DE USUARIO Y CONTRASENIA
CREATE USER JESUS IDENTIFIED BY JESUS1234;

--OTORGAR PRIVILEGIOS 
GRANT ALL PRIVILEGES TO JESUS;

