/*
    UN CURSOR ES UN MECANISMO QUE USA PL/SQL PARA RECORRER REGISTROS DE UNA
    CONSULTA SQL DE FILA EN FILA.
    
    CUANDO EJECUTAMOS UN SELECT EN PL/SQL QUE DEVUELVE UNA SOLA FILA, SE PUEDE
    USAR SELECT..INTO, PERO SI EL SELECT DEVUELVE VARIAS FILAS, NECESITAS UN 
    CURSOR PARA RECORRERLAS UNA A UNA. 
    
    TIPOS
        CURSORES IMPLICITOS
            -SE CREAN AUTOMATICAMENTE CUANDO EJECUTAS UN INSERT, UPDATE, DELETE
                O SELECT--INTO.
            -NO NECESITAS DECLARARLOS.
        CURSORES EXPLICITOS
            -LOS DECLARAS
            -SE USAN PARA RECORRER RESULTADOS DE UN SLEECT QUE DEVUELVE VARIAS
                FILAS.
            - TIENE 4 PASOS: DECLARAR -> ABRIR -> RECUPERAR 
                (LOS DATOS QUE DEVUELVE EL CURSOR) -> CERRAR
*/

--EJEMPLO DE CURSOR IMPLICITO
BEGIN
    UPDATE CELULAR SET PRECIO = PRECIO * 1.1 WHERE ID_CELULAR = 1;
    dbms_output.put_line(SQL%ROWCOUNT || '1 CELULARES AFECTADOS.');
END;
/

--EJEMPLO DE CURSOR EXPLICITO
CREATE OR REPLACE PROCEDURE DETALLE_CELULARES
IS
    CURSOR C_CELULARES_LISTA IS
        SELECT MARCA, MODELO, PRECIO FROM CELULAR;
    
    --ASEGURAMOS QUE LA VARIABLE SE RELACIONE CON LA COLUMNA DE LA TABLA
    V_MARCA CELULAR.MARCA%TYPE;
    V_MODELO CELULAR.MODELO%TYPE;
    V_PRECIO CELULAR.PRECIO%TYPE;
BEGIN
    OPEN C_CELULARES_LISTA;
    LOOP
        --RECUPERACION DE LA FILA
        FETCH C_CELULARES_LISTA INTO V_MARCA, V_MODELO, V_PRECIO;
        -- SALIR CUANDO NO ENCUENTRE NINGUNA FILA
        EXIT WHEN C_CELULARES_LISTA%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('EL CELULAR; ' || V_MARCA || ' ' || V_MODELO ||
            ' TIENE UN PRECIO DE: ' || V_PRECIO);
    END LOOP;
    CLOSE C_CELULARES_LISTA;
END;
/
EXECUTE DETALLE_CELULARES;