-- SENTENCIA PARA LA RECUPERACION DE INFORMACION, USUARIO, FECHA, AUTOINCREMENTO
-- AL ID_BIT

SELECT USER FROM DUAL; --RECUPERACION DE USUARIO DL SISTEMA
SELECT SYSDATE FROM DUAL; --RECUPERACION DE LA FECHA DEL SISTEMA

-- CAMBIA EL FORMATO DE FECHA DEL SISTEMA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YY HH24:MI:SS'; 

--CREAR AUTOINCREMENTO AL ID_BIT
-- NVL MANEJA LOS VALORES NULOS DE UNA VARIABLE, LO ASIGNA A 0
-- ENCONTRARA EL VALOR QUE SEGUIRIA
SELECT NVL(MAX(ID_BIT), 0) + 1 FROM CELULAR_BIT;

SELECT * FROM CELULAR;
SELECT * FROM celular_bit ORDER BY ID_BIT;
INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'GALAXY F3', '4GB', 'OCTACORE', 5000);
INSERT INTO CELULAR VALUES (2, 'SAMSUNG', 'GALAXY F4', '4GB', 'OCTACORE', 7000);
COMMIT;

DELETE FROM celular_bit;
DELETE FROM CELULAR WHERE id_celular = 2;
DELETE FROM celular_bit WHERE celular_bit.id_bit = 2;
COMMIT;

UPDATE CELULAR
SET 
    RAM = '6GB'
WHERE ID_CELULAR = 2;
COMMIT;
