/*EJERCICIO DE PRACTICA PARA USO DE PROCEDIMIETO

*/

/*1.- VAN CREAR LA TABLA PARA LA ENTIDAD TRABAJADOR
SUS ATRIBUTOS SON ID,NOMBRE, APELLIDO,PUESTO,
DEPARTAMENTO,SUELDO*/
CREATE TABLE TRABAJADOR(
    ID_TRABAJADOR NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    SUELDO NUMBER,
    CONSTRAINT TRABAJADOR_PK PRIMARY KEY (ID_TRABAJADOR)
);

--2.-AGREGAR POR LO MENOS 10 REGISTROS 
INSERT INTO TRABAJADOR VALUES (1, 'GIYU', 'TOMIOKA', 'PILAR DEL AGUA', 
    'CAZADORES DE DEMONIOS', 100000);
INSERT INTO TRABAJADOR VALUES (2, 'KYOJURO', 'RENGOKU', 'PILAR DEL FUEGO', 
    'CAZADORES DE DEMONIOS', 200000);
INSERT INTO TRABAJADOR VALUES (3, 'SHINOBU', 'KOCHO', 'PILAR DEL INSECTO', 
    'CAZADORES DE DEMONIOS', 200000);
INSERT INTO TRABAJADOR VALUES (4, 'NAOFUMI', 'IWATANI', 'SANTO DEL AVE DIVINA', 
    'HEROES', 100000);
INSERT INTO TRABAJADOR VALUES (5, 'MITSURI', 'KANROJI', 'PILAR DEL AMOR', 
    'CAZADORES DE DEMONIOS', 100000);
INSERT INTO TRABAJADOR VALUES (6, 'MAKI', 'ZENIN', 'LUCHADORA A', 
    'HECHICEROS', 20000);
INSERT INTO TRABAJADOR VALUES (7, 'GYOMEI', 'HIMEJIMA', 'PILAR DE LA ROCA', 
    'CAZADORES DE DEMONIOS', 300000);
INSERT INTO TRABAJADOR VALUES (8, 'SANEMI', 'SHINAZUWAWA', 'PILAR DE LA SERPIENTE', 
    'CAZADORES DE DEMONIOS', 200000);
INSERT INTO TRABAJADOR VALUES (9, 'PETER', 'PARKER', 'SPIDER-MAN', 
    'HEROES', 1000);
INSERT INTO TRABAJADOR VALUES (10, 'SATORU', 'GOJO', 'PROFESOR ESPECIAL', 
    'HECHIZEROS', 50000);
    
SELECT * FROM TRABAJADOR;

/*3.-REALIZAR LOS SIGUEINTES PROCEDURE*/
-- 1.-PROCDIMIENTO PARA CONSULTAR EL SUELDO DE UN TRABAJADOR
CREATE OR REPLACE PROCEDURE CONSULTA_SUELDO_TRABAJADOR(P_ID IN NUMBER)
IS 
    LV_ID_TRABAJADOR NUMBER;
    LV_SUELDO NUMBER;
    LV_TRABAJADOR_NOMBRE NVARCHAR2(100);
    LV_TRABAJADOR_APELLIDO NVARCHAR2(100);
BEGIN
    SELECT ID_TRABAJADOR, NOMBRE, APELLIDO, SUELDO INTO LV_ID_TRABAJADOR, 
        LV_TRABAJADOR_NOMBRE, LV_TRABAJADOR_APELLIDO, LV_SUELDO
    FROM TRABAJADOR WHERE ID_TRABAJADOR = P_ID;
    
    DBMS_OUTPUT.PUT_LINE('EL SUELDO DEL TRABAJADOR '|| LV_ID_TRABAJADOR 
        || '.- '|| lv_trabajador_nombre || ' ' 
        || lv_trabajador_apellido || ' ES ' || LV_SUELDO);
END;
/

EXECUTE CONSULTA_SUELDO_TRABAJADOR(10);


-- 2.-PROCEDIMIENTO PARA AUMENTAR EL SUELDO DE LOS TRABAJADORES
CREATE OR REPLACE PROCEDURE APLICAR_AUMENTO_TRABAJADOR(P_AUMENTO IN NUMBER) -- EN %
IS 
BEGIN
    UPDATE TRABAJADOR 
    SET SUELDO = SUELDO + (SUELDO * (P_AUMENTO / 100));
    
    DBMS_OUTPUT.PUT_LINE('SE APLICO EL AUMENTO DEL '|| P_AUMENTO || 
        '% A TODOS LOS TRABAJADORES');
END;
/
EXECUTE APLICAR_AUMENTO_TRABAJADOR(10);


-- 3.-PROCEDIMIENTO PARA BUSCAR UN TRABJADOR POR SU NOMBRE
