/* REALIZA LAS SIGUIENTES FUNCIONES*/
-- 1. CALCULA EL AREA DE UN TRIANGULO
CREATE OR REPLACE FUNCTION AREA_TRIANGULO(BASE NUMBER, ALTURA NUMBER)
RETURN NUMBER IS
BEGIN
    RETURN (BASE * ALTURA)/2;
END;
/
SELECT AREA_TRIANGULO(2, 3) AS AREA_TRIANGULO FROM DUAL;

--2. CREA UNA FUNCION QUE RECIBA UN NUMERO Y DEVUELVA SI ES PAR O IMPAR
CREATE OR REPLACE FUNCTION POI(NUMERO NUMBER)
RETURN NVARCHAR2 IS
BEGIN
    IF MOD(NUMERO, 2) = 0 THEN
        RETURN 'PAR';
    ELSE
        RETURN 'IMPAR';
    END IF;
END;
/
SELECT POI(5) AS PAR_O_IMPAR FROM DUAL;

-- 3.Calcular la edad a partir de una fecha de nacimiento
CREATE OR REPLACE FUNCTION CALCULAR_EDAD(FECHA_NACIMIENTO DATE)
RETURN NUMBER IS
    LV_FECHA_ACTUAL DATE;
    LV_ANIO_FECHA_NACIMIENTO NUMBER;
    LV_ANIO_FECHA_ACTUAL NUMBER;
BEGIN
    LV_FECHA_ACTUAL := SYSDATE;
    lv_anio_fecha_nacimiento := EXTRACT(YEAR FROM FECHA_NACIMIENTO);
    LV_ANIO_FECHA_ACTUAL := EXTRACT(YEAR FROM LV_FECHA_ACTUAL);
    RETURN lv_anio_fecha_actual - lv_anio_fecha_nacimiento;
END;
/
SELECT CALCULAR_EDAD(TO_DATE('25-01-2019', 'DD-MM-YYYY')) AS EDAD FROM DUAL;

--4. RECIBE LOS PARAMETROS DE NOMBRE Y APELLIDO Y DEVUELVE LAS INICIALES
CREATE OR REPLACE FUNCTION OBTEN_INICIALES_NOMBRE_APELLIDO(NOMBRE NVARCHAR2, APELLIDO NVARCHAR2)
RETURN NVARCHAR2 IS
    LV_INICIAL_NOMBRE NVARCHAR2(1);
    LV_INICIAL_APELLIDO NVARCHAR2(1);
BEGIN
    lv_inicial_nombre := SUBSTR(NOMBRE, 1, 1);
    lv_inicial_apellido := SUBSTR(APELLIDO, 1, 1);
    RETURN 'INICIAL NOMBRE: '||lv_inicial_nombre||' INICIAL APELLIDO: '
    ||lv_inicial_apellido;
END;
/
SELECT OBTEN_INICIALES_NOMBRE_APELLIDO('JESUS', 'RODRIGUEZ') AS INICIALES FROM DUAL;

-- 5.DEVUELVE EL NOMBRE DEL MES CORRESPONDIENTE SEGUN UN PARAMETRO RECIBIDO 
-- DEL 1 AL 12
CREATE OR REPLACE FUNCTION OBTEN_MES(MES NUMBER)
RETURN NVARCHAR2 IS
    -- Declara un tipo de VARRAY con un tamaño máximo de 12
    TYPE t_meses IS VARRAY(12) OF NVARCHAR2(15);    
    MESES t_meses := t_meses('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 
        'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 
        'DICIEMBRE');
BEGIN
    IF MES BETWEEN 1 AND 12 THEN
        RETURN MESES(MES);
    ELSE
        RETURN 'NO EXISTE UN MES CON ESE NUMERO';
    END IF;
END;
/
