-- REALIZA EL SIGUIENTE EJERCICIO 

/*


 
 
 
 
 
 
 7.ORDENAR LAS FUNCIONAS PRIMEROS POR GENERO Y LUEGO
 POR DURACION(ES SOLO UN CONSULTA)
 8.MOSTRAR EL DETALLE DE LAS FUNCIONES CON PIPES ||
 "LA PELICULA EL TITANICA SE PROYECTA EN LA SALA VIVALDI
 DE TIPO VIP CON UNA DURACION DE 120 MINUTOS"
 9.MOSTRAR EL GENERO QUE MAS FUNCIONES REGISTRADAS TIENE
*/

/*1.CREA LA TABLA SALA SUS CAMPOS SON ID_SALA, NOMBRE,
CAPACIDAD, TIPO(1.-TRADICIONAL,2.-VIP,3.-IMAX)*/
CREATE TABLE SALA (
    ID_SALA NUMBER,
    NOMBRE NVARCHAR2(100),
    CAPACIDAD NUMBER,
    TIPO NUMBER,
    CONSTRAINT ID_SALA_PK PRIMARY KEY (ID_SALA)
);

/*2.AGREGAR POR LO MENOS 6 REGISTROS(INCLUIR ALGUNOS
VALORES NULOS)*/
INSERT INTO SALA VALUES (1, 'SALA A', 80, 1);
INSERT INTO SALA VALUES (2, 'LA HD', 90, 3);
INSERT INTO SALA VALUES (3, 'LE SALE', 100, 2);
INSERT INTO SALA VALUES (4, 'SALA B', 80, 1);
INSERT INTO SALA VALUES (5, 'LA PODEROSA', 90, 3);
INSERT INTO SALA VALUES (6, 'SALA C', 80, 1);
commit;

/*3.CREAR LA TABLA FUNCION SUS CAMPOS SON ID_FUNCION,
PELICULA, DURACION_MIN, GENERO, PRECIO_BOLETO, SALA_ID*/
CREATE TABLE FUNCION (
    ID_FUNCION NUMBER,
    PELICULA NVARCHAR2(100),
    DURACION_MIN NUMBER,
    GENERO NVARCHAR2(100),
    PRECIO_BOLETO NUMBER,
    SALA_ID NUMBER,
    CONSTRAINT ID_FUNCION_PK PRIMARY KEY (ID_FUNCION),
    CONSTRAINT SALA_FK FOREIGN KEY (SALA_ID) REFERENCES SALA (ID_SALA)
);

/*4.AGREGAR POR LOS MENOS 6 REGISTROS(INCLUIR ALGUNOS
VALORES NULOS)*/
INSERT INTO FUNCION VALUES(1, 'DRACULA, DE BRAM STOKER', 127, 'TERROR', 160, 3);
INSERT INTO FUNCION VALUES(2, 'CREPUSCULO', -60, 'BASURA', -200, NULL);
INSERT INTO FUNCION VALUES(3, 'K-POP DEMON HUNTERS', 96, 'ANIMADA', 80, 1);
INSERT INTO FUNCION VALUES(4, 'KIMETSU NO YAIBA: INFINITY CASTLE', 155, 'ANIMADA', 120, 2);
INSERT INTO FUNCION VALUES(5, 'EMILIA PEREZ', -120, 'BASURA', -400, NULL);
INSERT INTO FUNCION VALUES(6, 'SPIDER-MAN 2', 141, 'SUPER HEROES', 120, 5);
COMMIT;

--5. REALIZAR LAS SIGUIENTES CONSULTAS 
/*5.1.MOSTRAR TODAS LA FUNCIONES CON EL NOMBRE DE LA SALA
 Y EL TIPO DE SALA USANDO CASE.*/
 SELECT F.PELICULA, S.NOMBRE, S.TIPO_SALA FROM 
 FUNCION F INNER JOIN (
    SELECT ID_SALA, NOMBRE,
    CASE 
    WHEN TIPO = 1 THEN 'TRADICIONAL'
    WHEN TIPO = 2 THEN 'VIP'
    WHEN TIPO = 3 THEN 'IMAX'
    END
     AS TIPO_SALA FROM SALA
 ) S
 ON F.SALA_ID = S.ID_SALA;
 
/*5.2.CONTAR CUANTAS FUNCIONES HAY POR GENERO*/
SELECT GENERO, COUNT(*) AS NUMERO_FUNCIONES FROM FUNCION GROUP BY GENERO;

/*5.3.MOSTRAR LA FUNCION CON EL BOLETO MAS CARO Y AGREGAR 
 LA PALABRA "PESOS" AL FINAL*/
SELECT * FROM FUNCION;
 SELECT 'LA FUNCION MAS CARA ES: '||PELICULA||' Y SU BOLETO CUESTA '
 ||PRECIO_BOLETO||' PESOS' AS DETALLE FROM FUNCION F
 INNER JOIN (SELECT MAX(PRECIO_BOLETO) AS BOLETO_MAS_CARO FROM FUNCION) B
 ON f.precio_boleto = B.boleto_mas_caro;

/*5.4.MOSTRAR EL TOTAL DE BOLETOS QUE PODRIA VENDER CADA
 FUNCION(CAPACIDAD DE LA SALA * PRECIO BOLETO)*/
 SELECT f.pelicula, f.precio_boleto, s.capacidad, (
 CASE 
 WHEN f.precio_boleto is NULL then 0
 when s.capacidad is NULL then 0
 else f.precio_boleto * s.capacidad
 END
 ) AS VENTA_MAX_BOLETOS FROM FUNCION F
 FULL JOIN SALA S
 ON F.SALA_ID = S.ID_SALA;
 
 SELECT f.pelicula, f.precio_boleto, s.capacidad FROM FUNCION F
 FULL JOIN SALA S
 ON F.SALA_ID = S.ID_SALA;
 
/*5.5.-MOSTRAR LA SALA CON MAYOR ACPACIDAD Y CONCATENAR EL
 RESULTADO CON LA PALBRA "ASiENTOS"*/
 SELECT 'LA SALA CON MAYOR CAPACIDAD ES "'||S.NOMBRE||'" CON '||S.CAPACIDAD||
 ' ASIENTOS' AS DETALLE FROM SALA S
 INNER JOIN (SELECT MAX(CAPACIDAD) AS MAYOR_CAPACIDAD FROM SALA) M
 ON S.CAPACIDAD = M.MAYOR_CAPACIDAD;
 
/*5.6.MOSTRAR LAS FUNCIONES QUE NO TIENEN SALA ASIGNADA*/
SELECT F.PELICULA, S.NOMBRE AS NOMBRE_SALA
FROM FUNCION F LEFT JOIN SALA S
ON F.SALA_ID = S.ID_SALA
WHERE F.SALA_ID IS NULL;

/*5.*/
/*5.*/
/*5.*/