-- 1.CREAR UNA TABLA ALUMNO(ID, NOMBRE, EDAD, CARRERA, PROMEDIO, GENERO(M o F)
CREATE TABLE ALUMNO(
	ID_ALUMNO NUMBER,
	NOMBRE NVARCHAR2(50), 
	EDAD NUMBER,
	CARRERA NVARCHAR2(50),
	PROMEDIO NUMBER, 
	GENERO NVARCHAR2(50),
	CONSTRAINT ALUMNO_PK PRIMARY KEY(ID_ALUMNO)
);

-- 2.- INSERTAR POR LO MENOS 7 VALORES
INSERT INTO ALUMNO VALUES (1, 'RAUL', 29, 'LIC. EN MEDICINA', 7, 'M');
INSERT INTO ALUMNO VALUES (2, 'LISA', 36, 'LIC. EN MUSICA', 10, 'F');
INSERT INTO ALUMNO VALUES (3, 'TEIO', 20, 'LIC. EN DEPORTE', 10, 'F');
INSERT INTO ALUMNO VALUES (4, 'GOJO', 31, 'LIC. EN EDUCACION', 8, 'M');
INSERT INTO ALUMNO VALUES (5, 'SCARLET', 20, 'LIC. EN DEPORTE', 10, 'F');
INSERT INTO ALUMNO VALUES (6, 'FLOW', 35, 'LIC. EN MUSICA', 7, 'M');
INSERT INTO ALUMNO VALUES (7, 'AIMER', 31, 'LIC. EN MUSICA', 10, 'F');
commit;


-- 3.- REALIZAR LAS SIGUIENTES CONSULTAS
-- 3.1.-MOSTRAR TODOS LOS ALUMNOS REGISTRADOS
SELECT * FROM ALUMNO;

-- 3.2.-MOSTRAR EL NOMBRE Y CARRERA DE TODOS LOS ALUMNOS
SELECT NOMBRE, CARRERA FROM ALUMNO;

-- 3.3.- MOSTRAR LOS NOMBRES Y PROMEDIOS DE LOS ALUMNOS CON PROMEDIO MAYOR A 8.0
SELECT NOMBRE, PROMEDIO FROM ALUMNO WHERE PROMEDIO > 7;

-- 3.4.- MOSTRAR LOS ALUMNOS QUE PERTENECEN A LA CARRERA DE MUSICA
SELECT * FROM ALUMNO WHERE CARRERA LIKE 'LIC. EN MUSICA';

-- 3.5.- MOSTRAR LOS ALUMNOS CUYA EDAD SEA MAYOR O IGUAL A 22 ANIOS
SELECT * FROM ALUMNO WHERE EDAD > 21;

-- 3.6.-MOSTRAR LOS ALUMNOS ORDENADOS POR APELLIDO(A A LA Z)
SELECT * FROM ALUMNO ORDER BY NOMBRE ASC;

-- 3.7.-MOSTRAR LOS ALUMNOS DE GENERO FEMENINO
SELECT * FROM ALUMNO WHERE GENERO LIKE 'F';

-- 3.8.-MOSTRAR LOS ALUMNNOS ORDENADOS POR PROMEDIO(EL MAS BAJO AL MAS ALTO)
SELECT * FROM ALUMNO ORDER BY PROMEDIO ASC;

-- 3.9.-CONTAR CUANTOS ALUMNOS HAY EN TOTAL
SELECT COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS FROM ALUMNO;

-- 3.10.-CONTAR CUANTOS ALUMNOS HAY POR CARRERA
SELECT COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS, CARRERA FROM ALUMNO GROUP BY CARRERA;
 
-- 3.11.-MOSTRAR EL PROMEDIO GENERAL DE TODOS LOS ALUMNOS
SELECT AVG(PROMEDIO) AS PROMEDIO_TOTAL FROM ALUMNO;

-- 3.12.-MOSTRAR AL ALUMNOS CON EL MEJOR PROMEDIO 
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MAX(PROMEDIO) FROM ALUMNO);

-- 3.13.-MOSTRAR AL ALUMNO CON EL PEOR PROMEDIO
SELECT * FROM ALUMNO WHERE PROMEDIO = (SELECT MIN(PROMEDIO) FROM ALUMNO);

-- 3.14.-MOSTRAR LA EDAD PROMEDIO DE LOS ALUMNOS DE MUSICA
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM ALUMNO;

-- 3.15.-MOSTRAR CUANTOS ALUMNOS SON HOMBRES Y CUANTOS SON MUJERES.
SELECT COUNT(ID_ALUMNO) AS TOTAL_ALUMNOS, GENERO FROM ALUMNO GROUP BY GENERO;

-- 3.16.-MOSTRAR LOS ALUMNOS CUYO NOMBRE INCIE EN M
SELECT * FROM ALUMNO WHERE NOMBRE LIKE 'L%';

-- 3.17.- DAR UN FORMATO CON PIPE || EJE: EL ALUMNO GERARDO JIMENES DE EDAD 23, 
-- CURSA LA CARRERA DE SISTEMAS CON UN PROMEDIO DE 8.9

SELECT 'EL ALUMNO: '||NOMBRE||' DE GENERO: '||GENERO||' DE EDAD: '||EDAD||
' ESTUDIA EN: '||CARRERA||' CON UN PROMEDIO DE:  '||PROMEDIO  
    AS DETALLE FROM ALUMNO;