--PRACTICA 2: CONSULTAS CASE

/*


    
    
    
    
    5.-CLASIFICA LAS COMPUTADORAS POR ANTIGUEDAD.
*/

-- 1.- CREAR LA TABLA COMPUTADORA
CREATE TABLE COMPUTADORA (
	ID_COMPUTADORA NUMBER, 
	MARCA NVARCHAR2(50), 
	RAM NUMBER,
	ALMACENAMIENTO NUMBER, 
	PROCESADOR NVARCHAR2(50),
	TIPO NUMBER, -- (1.ESCRITORIO,2.PORTATIL,3TABLET4.TODOENUNO)
	PRECIO NUMBER, 
	FECHA_COMPRA DATE,
	CONSTRAINT COPMUTADORA_PK PRIMARY KEY(ID_COMPUTADORA)
);
	
-- 2.-AGREGAR POR LO MENOS 7 REGISTROS 
INSERT INTO COMPUTADORA VALUES (1, 'Dell', 16, 512, 'Intel Core i7', 1, 12500, TO_DATE('17-09-2023', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (2, 'HP', 8, 256, 'AMD Ryzen 5', 1, 8900, TO_DATE('05-03-2024', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (3, 'Apple', 16, 1000, 'M2', 2, 25000, TO_DATE('20-01-2025', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (4, 'Lenovo', 32, 1000, 'Intel Core i9', 1, 19800, TO_DATE('10-10-2024', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (5, 'Asus', 16, 512, 'AMD Ryzen 7', 1, 14750, TO_DATE('14-06-2024', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (6, 'Acer', 8, 256, 'Intel Core i5', 1, 7500, TO_DATE('22-11-2023', 'DD-MM-YYYY'));
INSERT INTO COMPUTADORA VALUES (7, 'Microsoft', 16, 512, 'Intel Core i7', 2, 18200, TO_DATE('30-04-2024', 'DD-MM-YYYY'));

-- 3.- REALIZAR LOS SIGUIENTE EJERICICOS
-- 3.1.CLASIFICA LAS COMPUTADORAS POR CAPACIDAD DE RAM
SELECT ID_COMPUTADORA, MARCA, (
	CASE  
	WHEN RAM < 8 THEN 'LENTA'
	WHEN RAM BETWEEN 9 AND 16 THEN 'ESTANDAR'
	WHEN RAM BETWEEN 17 AND 32 THEN 'ALTA'
	ELSE 'MUY ALTA'
	END
) AS CAPACIDAD_DE_RAM, RAM FROM COMPUTADORA;

-- 3.2.CLASIFICA LAS COMPUTADORA POR PRECIO
SELECT ID_COMPUTADORA, MARCA, (
	CASE  
	WHEN PRECIO < 5000 THEN 'ECONOMICA'
	WHEN PRECIO BETWEEN 5001 AND 10000 THEN 'BARATA'
	WHEN PRECIO BETWEEN 10000 AND 15000 THEN 'CARA'
	ELSE 'DE LUJO'
	END
) AS LUJOSIDAD, PRECIO FROM COMPUTADORA;

-- 3.3.CLASIFICA LAS COMPUTADORS POR CAPACIDAD DE ALMACENAMIENTO.
SELECT ID_COMPUTADORA, MARCA, (
	CASE  
	WHEN ALMACENAMIENTO < 257 THEN 'BAJO ALMACENAMIENTO'
	WHEN ALMACENAMIENTO BETWEEN 257 AND 512 THEN 'ALMACENAMIENTO MODERADO'
	ELSE 'GRAN ALMACENAMIENTO'
	END
) AS CEREBRON, ALMACENAMIENTO FROM COMPUTADORA;

-- 3.4.-MUESTRA LA INFORMACION DE LA COMPUTADORA CON SU RESPECTIVO TIPO

-- 3.