/*ACTIVIDAD*/
-- realizar las siguientes vistas sobre la tabla trabajador

select * from trabajador;

-- 1. UNA VISTA QUE MUESTRE EL NOMBRE, DEPARTAMENTO Y PUESTO DE TODOS LOS 
-- TRABAJADORES
CREATE OR REPLACE VIEW V_NAME_DEPT_PUESTO_TRABAJADOR AS
SELECT NOMBRE, DEPARTAMENTO, PUESTO
FROM TRABAJADOR;

SELECT * FROM V_NAME_DEPT_PUESTO_TRABAJADOR;

-- 2. UNA VISTA QUE MUESTRE EL NOMBRE Y EDAD DE LOS EMPLEADOS DEL DEPARTAMENTO
-- DE TECNOLOGIA
INSERT INTO TRABAJADOR VALUES (11, 'JESUS', 'RODRIGUEZ', 'PROGRAMADOR JAVA', 
    'TECNOLOGIA', 30000);
INSERT INTO TRABAJADOR VALUES (12, 'MARIO', 'CASTILLO', 'PROGRAMADOR JAVA', 
    'TECNOLOGIA', 20000);
    
CREATE OR REPLACE VIEW V_TRABAJADORES_DEPT_TECNOLOGIA AS
SELECT NOMBRE, APELLIDO
FROM TRABAJADOR
WHERE DEPARTAMENTO = 'TECNOLOGIA';

SELECT * FROM V_TRABAJADORES_DEPT_TECNOLOGIA;

-- 3.- UNA VISTA QUE MUESTRE LOS TRABAJADORES QUE GANAN MENOS DE 7000
CREATE OR REPLACE VIEW V_TRABAJADORES_MALPAGADOS AS
SELECT NOMBRE, APELLIDO
FROM TRABAJADOR
WHERE SUELDO < 7000;

SELECT * FROM V_TRABAJADORES_MALPAGADOS;

-- 4 UNA VISTA QUE MUESTRE EL NOMBRE, APELLIDO Y DEPARTAMENTO DE LOS 
-- TRABAJADORES Y LOS CATALOGUE POR SUELDO.
CREATE OR REPLACE VIEW V_NSE_TRABAJADOR AS
SELECT NOMBRE, APELLIDO, DEPARTAMENTO, 
    CASE
        WHEN SUELDO > 30000 THEN 'CLASE ALTA' 
        WHEN SUELDO BETWEEN 15000 AND 30000 THEN 'CLASE MEDIA'
        WHEN SUELDO < 150000 THEN 'CLASE BAJA'
    END AS NSE
FROM TRABAJADOR;

SELECT * FROM V_NSE_TRABAJADOR;