/*EJECRICIO DE PRACTICA

REALIZAR LAS PRUEBAS EN AMBOS TRIGGER.
*/

drop table opening
-- 1.- CREAR UNA ENTIDAD
CREATE TABLE OPENING (
    ID_OPENING NUMBER,
    NOMBRE_OPENING NVARCHAR2(100),
    NOMBRE_AUTOR NVARCHAR2(100),
    NOMBRE_ANIME_ASIGNADO NVARCHAR2(100),
    NUMERO_OPENING_ANIME NUMBER,
    FECHA_LANZAMIENTO DATE,
    DURACION_SEGUNDOS NUMBER,
    CONSTRAINT OPENING_PK PRIMARY KEY (ID_OPENING)
);

DROP TABLE BITACORA_OPENING;
-- 2.- CREAR LA BITACORA DE ESA ENTIDAD
CREATE TABLE BITACORA_OPENING(
    ID_BITACORA_OPENING NUMBER,
    OPENING_ID NUMBER,
    
    --VALORES NUEVOS :NEW
    NOMBRE_OPENING NVARCHAR2(100),
    NOMBRE_AUTOR NVARCHAR2(100),
    NOMBRE_ANIME_ASIGNADO NVARCHAR2(100),
    NUMERO_OPENING_ANIME NUMBER,
    FECHA_LANZAMIENTO DATE,
    DURACION_SEGUNDOS NUMBER,
    
    --VALORES VIEJOS :OLD
    NOMBRE_OPENING_OLD NVARCHAR2(100),
    NOMBRE_AUTOR_OLD NVARCHAR2(100),
    NOMBRE_ANIME_ASIGNADO_OLD NVARCHAR2(100),
    NUMERO_OPENING_ANIME_OLD NUMBER,
    FECHA_LANZAMIENTO_OLD DATE,
    DURACION_SEGUNDOS_OLD NUMBER,
    
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT BITACORA_OPENING_PK PRIMARY KEY (ID_BITACORA_OPENING)
);

-- 3.- CREAR LA SEQUENCIA PARA APLICAR Y UTILIZAR CON ESA ENTIDAD
CREATE SEQUENCE ID_BIT_OP_SEQ
START WITH 1
MINVALUE 1
MAXVALUE 99
NOCYCLE;

-- 4.- CREAR UN TRIGGER MULTIPLE DE TIPO AFTER A NIVEL FILA
CREATE OR REPLACE TRIGGER TR_ROW_MULTI_OPENING
AFTER INSERT OR UPDATE OR DELETE ON OPENING
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    --RECUPERAR UN ID VALIDO USANDO SECUENCIAS
    SELECT ID_BIT_OP_SEQ.NEXTVAL, USER, SYSDATE
    INTO LV_ID_BIT, LV_USUARIO, LV_FECHA 
    FROM DUAL;
    
    IF INSERTING THEN
        INSERT INTO BITACORA_OPENING(ID_BITACORA_OPENING, OPENING_ID, 
            NOMBRE_OPENING, NOMBRE_AUTOR, NOMBRE_ANIME_ASIGNADO, 
            NUMERO_OPENING_ANIME, FECHA_LANZAMIENTO, DURACION_SEGUNDOS, USUARIO,
            FECHA_MOV, MOVIMIENTO) 
        VALUES (LV_ID_BIT, :NEW.ID_OPENING, :NEW.NOMBRE_OPENING, 
            :NEW.NOMBRE_AUTOR, :NEW.NOMBRE_ANIME_ASIGNADO, 
            :NEW.NUMERO_OPENING_ANIME, :NEW.FECHA_LANZAMIENTO, 
            :NEW.DURACION_SEGUNDOS, LV_USUARIO, 
            LV_FECHA, 'INSERT');
    ELSIF UPDATING THEN
        INSERT INTO BITACORA_OPENING(ID_BITACORA_OPENING, OPENING_ID,
            NOMBRE_OPENING, NOMBRE_AUTOR, NOMBRE_ANIME_ASIGNADO, 
            NUMERO_OPENING_ANIME, FECHA_LANZAMIENTO, DURACION_SEGUNDOS, 
            NOMBRE_OPENING_OLD, NOMBRE_AUTOR_OLD, 
            NOMBRE_ANIME_ASIGNADO_OLD, NUMERO_OPENING_ANIME_OLD, 
            FECHA_LANZAMIENTO_OLD, DURACION_SEGUNDOS_OLD, USUARIO, 
            FECHA_MOV, MOVIMIENTO) 
        VALUES (LV_ID_BIT, :NEW.ID_OPENING, :NEW.NOMBRE_OPENING, 
            :NEW.NOMBRE_AUTOR, :NEW.NOMBRE_ANIME_ASIGNADO, 
            :NEW.NUMERO_OPENING_ANIME, :NEW.FECHA_LANZAMIENTO, 
            :NEW.DURACION_SEGUNDOS, :OLD.NOMBRE_OPENING, 
            :OLD.NOMBRE_AUTOR, :OLD.NOMBRE_ANIME_ASIGNADO, 
            :OLD.NUMERO_OPENING_ANIME, :OLD.FECHA_LANZAMIENTO, 
            :OLD.DURACION_SEGUNDOS,LV_USUARIO, LV_FECHA, 'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO BITACORA_OPENING(ID_BITACORA_OPENING, OPENING_ID, 
            NOMBRE_OPENING_OLD, NOMBRE_AUTOR_OLD, NOMBRE_ANIME_ASIGNADO_OLD, 
            NUMERO_OPENING_ANIME_OLD, FECHA_LANZAMIENTO_OLD, 
            DURACION_SEGUNDOS_OLD, USUARIO, FECHA_MOV, MOVIMIENTO) 
        VALUES (LV_ID_BIT, :OLD.ID_OPENING, :OLD.NOMBRE_OPENING, 
            :OLD.NOMBRE_AUTOR, :OLD.NOMBRE_ANIME_ASIGNADO, 
            :OLD.NUMERO_OPENING_ANIME, :OLD.FECHA_LANZAMIENTO, 
            :OLD.DURACION_SEGUNDOS, LV_USUARIO, 
            LV_FECHA, 'DELETE');
    END IF;
END TR_MULTIPLE_CEL;

INSERT INTO OPENING (ID_OPENING, NOMBRE_OPENING, NOMBRE_AUTOR, 
    NOMBRE_ANIME_ASIGNADO, NUMERO_OPENING_ANIME, FECHA_LANZAMIENTO) 
VALUES (1, 'Shiny Ray', 'YURIKA', 'LITTLE WITCH ACADEMIA', 1, 
    (DATE '2017-02-22'));

UPDATE OPENING
SET DURACION_SEGUNDOS = 232
WHERE ID_OPENING = 1;

DELETE FROM OPENING WHERE ID_OPENING = 1;

SELECT * FROM OPENING;
SELECT * FROM BITACORA_OPENING;

-- 5.- CREAR UN TRIGGER MULTIPLE DE TIPO AFTER A NIVEL SENTENCIA
CREATE OR REPLACE TRIGGER TR_SENTENCIA_OP
AFTER INSERT OR UPDATE OR DELETE ON OPENING
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(10);
BEGIN
    SELECT ID_BIT_OP_SEQ.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, 
        LV_USUARIO, LV_FECHA
    FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATET';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
    
    INSERT INTO BITACORA_OPENING(ID_BITACORA_OPENING, USUARIO, FECHA_MOV, MOVIMIENTO)
    VALUES(LV_ID_BIT, LV_USUARIO, LV_FECHA, LV_MOV);
END;

SELECT ID_BITACORA_OPENING, USUARIO, FECHA_MOV, MOVIMIENTO FROM BITACORA_OPENING;
SELECT * FROM OPENING;

INSERT INTO OPENING (ID_OPENING, NOMBRE_OPENING, NOMBRE_AUTOR, 
    NOMBRE_ANIME_ASIGNADO, NUMERO_OPENING_ANIME, FECHA_LANZAMIENTO) 
VALUES (1, 'Shiny Ray', 'YURIKA', 'LITTLE WITCH ACADEMIA', 1, 
    (DATE '2017-02-22'));

UPDATE OPENING
SET DURACION_SEGUNDOS = 232
WHERE ID_OPENING = 1;

DELETE FROM OPENING WHERE ID_OPENING = 1;