/*REALIZAR COMO PRACTICA LOS SIGUIENTE EJERCICIOS
*/

/*
    1.- CALCULAR LA SUMA DE LOS DIGITOS DE UN NUMERO 
    EJEMPLO: V:=1234, SALIDA = 10.
*/
DECLARE
  LV_NUMERO NUMBER := 1234;
  LV_SUMA_DIGITOS NUMBER := 0;
  LV_TEMP_NUMERO NUMBER;
  LV_DIGITO NUMBER;
BEGIN
  -- COPIA DEL NUMERO ORIGINAL
  LV_TEMP_NUMERO := LV_NUMERO;

  WHILE LV_TEMP_NUMERO > 0 
    LOOP
        -- OBTIENE EL ULTIMO DIGITO CON AYUDA DE MODULO 10
        LV_DIGITO := MOD(LV_TEMP_NUMERO, 10);
        LV_SUMA_DIGITOS := LV_SUMA_DIGITOS + LV_DIGITO;
    
        -- ELIMINA EL ULTIMO DIGITO, CON AYUDA DE TRUNC
        LV_TEMP_NUMERO := TRUNC(LV_TEMP_NUMERO / 10);
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('LA SUMA DE LOS DIGITOS DEL NUMERO ' || LV_NUMERO || 
  ' ES ' || LV_SUMA_DIGITOS);
END;
/

/*
    2.- MOSTRAR LA CUENTA REGRESIVA DE 20 A 0 EN NUMEROS PARES
*/
DECLARE 
    LV_CUENTA_REGRESIVA NUMBER := 20;
BEGIN
    WHILE LV_CUENTA_REGRESIVA >= 0
    LOOP
        DBMS_OUTPUT.PUT_LINE('TIK TOK....'|| LV_CUENTA_REGRESIVA);
        LV_CUENTA_REGRESIVA := LV_CUENTA_REGRESIVA - 2;
    END LOOP;
END;
/

/*
    3.-CALCULAR LA POTENCIA DE UN NUMERO(3^4)
*/
DECLARE
    LV_NUMERO NUMBER := 3;
    LV_POTENCIA NUMBER := 4;
    LV_RESULTADO NUMBER := 1;
BEGIN
    IF LV_POTENCIA > 0 
        THEN FOR i IN 1..LV_POTENCIA
            LOOP
                LV_RESULTADO := LV_RESULTADO * LV_NUMERO;
            END LOOP;
    END IF;
    DBMS_OUTPUT.PUT_LINE(''|| LV_NUMERO || ' ELEVADO A ' || LV_POTENCIA || 
        ' ES ' || LV_RESULTADO);
END;
/

/*
    4.-MOSTRAR LOS CARACTERES DE TU NOMBRE 
    'VALOR' = A
    'VALOR' = L 
*/
DECLARE
  LV_NOMBRE NVARCHAR2(100) := 'Jesus';
  LV_NOMBRE_LENGTH NUMBER;
  LV_LETRA NVARCHAR2(1);
BEGIN
  LV_NOMBRE_LENGTH := LENGTH(LV_NOMBRE);
  
  FOR i IN 1..LV_NOMBRE_LENGTH 
    LOOP
        -- EXTRAE UN CARACTER EN LA POSICION ACTUAL
        LV_LETRA := SUBSTR(LV_NOMBRE, i, 1);
    DBMS_OUTPUT.PUT_LINE('' || i || '.- ' || LV_LETRA);
  END LOOP;
END;
/

/*
    5.-MOSTRAR SI UN NUMERO ES PRIMO
*/
DECLARE
    LV_NUMERO NUMBER := 7;
    LV_PRIMO NUMBER;
BEGIN
    LV_PRIMO := MOD(LV_NUMERO, 2);
    IF LV_PRIMO = 0 THEN DBMS_OUTPUT.PUT_LINE('' || LV_NUMERO || ' NO ES PRIMO ');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('' || LV_NUMERO || ' ES PRIMO ');
    END IF;
END;
/

/*
6.- MOSTRAR LAS TABLAS DE MILTIPLAR DEL 1 AL 10 
EJEMPLO TABLA DEL 1
        1 * 1 = 1
        ...
        TABLA DEL 2
*/
DECLARE
    LV_RESULTADO NUMBER;
BEGIN
    FOR i IN 1..10 LOOP
        DBMS_OUTPUT.PUT_LINE('TABLA DEL ' || i );
        FOR j IN 1..10 LOOP
            LV_RESULTADO := i*j;
            DBMS_OUTPUT.PUT_LINE('' || i || ' X ' || j || ' = '||LV_RESULTADO);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('====================');
    END LOOP;
END;
/