-- TABLA PARA EL MICROSERVICIO DE CLIENTE
CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    TIENDA_ID NUMBER,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);

CREATE SEQUENCE ID_CLIENTES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE OR REPLACE TRIGGER TR_ID_CLIENTES
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN 
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT ID_CLIENTES.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
    END IF;
END;
/

INSERT INTO CLIENTE (NOMBRE, APP, EDAD, TIENDA_ID)
VALUES('JOSE', 'DOMINGUEZ', 25, 1);
COMMIT

SELECT * FROM CLIENTE;